pipeline {
    agent any

    environment {
        IMAGE_NAME = "aanyaagg/employee-api:v1"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                bat 'mvn clean package'
            }
        }

        stage('Test') {
            steps {
                bat 'mvn test'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat "docker build -t %IMAGE_NAME% ."
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: '4e28f654-748a-4fc4-be40-1ba378b057e6',
                    DOCKER_USERNAME: 'aanyaagg',
                    DOCKER_PASSWORD: 'aanya2005'
                )]) {
                    bat 'echo %DOCKER_PASSWORD% | docker login -u %DOCKER_USERNAME% --password-stdin'
                }
            }
        }


        stage('Push Docker Image') {
            steps {
                bat "docker push %IMAGE_NAME%"
            }
        }

        stage('Run Docker Container') {
            steps {
                bat '''
                docker stop employee-container 2>nul
                docker rm employee-container 2>nul
                docker run -d -p 8081:8080 --name employee-container %IMAGE_NAME%
                '''
            }
        }
    }

    post {
        always {
            bat 'docker logout'
        }

        success {
            echo 'Pipeline completed successfully!'
        }

        failure {
            echo 'Pipeline failed!'
        }
    }
}
